apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: one-cluster-placement
  namespace: openshift-gitops
spec:
  numberOfClusters: 1
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: purpose
          operator: "In"
          values:
          - kss
  prioritizerPolicy:
    configurations:
      - name: ResourceAllocatableMemory
        weight: 2
